### ISSUE TITLE
Has any body been able to down load or clone the grbhal code and get it to compile in Visual studio??

### ISSUE THREAD

**Issue by ghost** [grblHAL/drivers#4]
Has any body been able to down load or clone the grbhal code and get it to compile in Visual studio on Ubuntu Linux?? Seems like many files are missing. On purpose? cloned all the files into a folder and get all kinds of errors. Doesn't matter which processor I try they all fail with different errors. Seems like the contributors are downloading partial updates and omitting VSC files needed to compile the code to a working file.

**Comment by andrewmarles** [comment]
The vast majority of people that have this problem have not cloned with --recursive or --recurse-submodules.  Many people have successfully compiled the code.  I have personally compiled and contributed to code for IMX1062, STM32F4xx and RP2040.  I've also watched people successfully clone the trees that I have published and compile their own code so it's not an issue with what is up on Github.

**Comment by ghost** [comment]
Will try your trees Already did the recursive clones. Still get error1 and VSC doesn't seem to find my pico-sdk install even though I export the $PATH
